baseURL = 'https://mcasrom.github.io/australia-blog/'
languageCode = 'es-es'
title = 'M. Castillo - Australia 2026'
theme = 'PaperMod'
publishDir = 'docs'

[params]
    defaultTheme = "light" # Forzamos luz para controlar el color
    showCodeCopyButtons = true
    
    [params.assets]
        # Inyectamos el CSS para el tono azul directamente
        customCSS = ["css/custom.css"]

[markup.goldmark.renderer]
    unsafe = true
