baseURL = 'https://mcasrom.github.io/australia-blog/'
languageCode = 'es-es'
title = 'M. Castillo - Australia 2026'
theme = 'PaperMod'
publishDir = 'docs'

[params]
    defaultTheme = "auto"
    showCodeCopyButtons = true

[markup.goldmark.renderer]
    unsafe = true # Por si metes HTML a mano en los posts
